version: '3.8'

services:
  app:
    image: python:3.12
    container_name: my_app
    working_dir: /app
    volumes:
      - /c/Computer-Systems-hw02:/app
    command: bash -c "pip install --no-cache-dir -r requirements.txt && pip install uvicorn && uvicorn main:app --host 0.0.0.0 --port 5000"
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:567234@db:5432/hw02
    depends_on:
      - db
    ports:
      - "5000:5000"

  db:
    image: postgres:13
    container_name: my_postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 567234
      POSTGRES_DB: hw02
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pg_data:
    driver: local
